baseURL: "https://mtutech.net/"
languageCode: en-us
title: "CodedTuna"
theme: "PaperMod"

menu:
  main:
    - identifier: about me
      name: About me
      url: /about me/
      weight: 20
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20

params:
  # home-info mode
    homeInfoParams:
      Title: "NOTICE: End of Support"
      Content: "NOTICE: This website will no longer be maintained/updated after **August of 2023**, please visit [here](https://ken20080601.wixsite.com/kentseng) for updated info, see you on the other side :)"

    socialIcons:
      - name: Github
        url: "https://github.com/KaichenTseng"
      - name: Stackoverflow
        url: "https://stackoverflow.com/users/21010116/ken-tseng"
      - name: Reddit
        url: "https://www.reddit.com/u/Puzzleheaded_sink_31"
      - name: Youtube
        url: "https://www.youtube.com/channel/UC-GAopTIBn1h7Wh4bE7EC3A"
      - name: Instagram
        url: "https://www.instagram.com/ken_twn.144/"
      - name: Pinterest
        url: "https://www.pinterest.nz/CCCP144/"
      - name: Meduim
        url: "https://medium.com/@ken20080601"