baseURL: "https://codedtuna.netlify.app/"
languageCode: en-us
title: "CodedTuna"
theme: "PaperMod"

menu:
  main:
    - identifier: about me
      name: About me
      url: /about me/
      weight: 20
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20

params:
  # home-info mode
    homeInfoParams:
      Title: "Hello Stranger."
      Content: This site's still under construction; perhaps return later :) ?

    socialIcons:
      - name: github
        url: "https://github.com/KaichenTseng"
      - name: stackoverflow
        url: "https://stackoverflow.com/users/21010116/ken-tseng"
      - name: reddit
        url: "https://www.reddit.com/u/Puzzleheaded_sink_31"
      - name: youtube
        url: "https://www.youtube.com/channel/UC-GAopTIBn1h7Wh4bE7EC3A"
      - name: instagram
        url: "https://www.instagram.com/tu_cccp.144/"
      - name: Pinterest
        url: "https://www.pinterest.nz/CCCP144/"
      - name: meduim
        url: "https://medium.com/@ken20080601"

languages:
  en:
    contentDir: content/english
    languageName: English
    weight: 10
  fr:
    contentDir: content/chinese
    languageName: Chinese
    weight: 20